/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.PersonaController;
import Excepciones.FechaInvalidaException;
import Modelo.Persona;
import Vista.Utilidades.Utilidades;
import Vista.modeloTabla.ModeloTablaPersona;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author David Campoverde
 */
public class FrmPrincipal extends javax.swing.JFrame {
    PersonaController pc = new PersonaController();
    ModeloTablaPersona mtp = new ModeloTablaPersona();
    DialogPersona diaPersona;
    DialogPracticas diaPractica;
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cargarTabla();
        setLocationRelativeTo(this);
    }
    
    public void cargarTabla(){
        if(pc.getPersonas() != null){
            mtp.setPersonas(pc.getPersonas());
            tblListadoPersonas.setModel(mtp);
            tblListadoPersonas.updateUI();
            jPanel2.setVisible(true);
        }else jPanel2.setVisible(false);
    }
    
    public void crearPersona(){
        diaPersona = new DialogPersona(this, true);
        diaPersona.setVisible(true);
        Persona p = diaPersona.getPersona();
        if(p != null){
            pc.getPersonas()[tblListadoPersonas.getSelectedRow()].setApellidos(p.getApellidos());
            pc.getPersonas()[tblListadoPersonas.getSelectedRow()].setNombres(p.getNombres());
            pc.getPersonas()[tblListadoPersonas.getSelectedRow()].setFechaNacimiento(p.getFechaNacimiento());
            pc.getPersonas()[tblListadoPersonas.getSelectedRow()].setGenero(p.getGenero());
        }
        try {
            pc.calcularEdades();
        } catch (FechaInvalidaException ex) {
            
        }
        pc.imprimirArreglo();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxNroPersonas = new javax.swing.JComboBox<>();
        btnCrear1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListadoPersonas = new javax.swing.JTable();
        btnAgregarPersona = new javax.swing.JButton();
        btnEditarPersona = new javax.swing.JButton();
        btnPracticas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Persona"));

        jLabel1.setText("Nro de Personas");

        cbxNroPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        btnCrear1.setText("Crear");
        btnCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(cbxNroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(btnCrear1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxNroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrear1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tblListadoPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListadoPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListadoPersonasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListadoPersonasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblListadoPersonas);

        btnAgregarPersona.setText("Agregar");
        btnAgregarPersona.setEnabled(false);
        btnAgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPersonaActionPerformed(evt);
            }
        });

        btnEditarPersona.setText("Editar");
        btnEditarPersona.setEnabled(false);
        btnEditarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPersonaActionPerformed(evt);
            }
        });

        btnPracticas.setText("Agregar Indicaciones");
        btnPracticas.setEnabled(false);
        btnPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPracticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregarPersona)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarPersona)
                        .addGap(18, 18, 18)
                        .addComponent(btnPracticas)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPersona)
                    .addComponent(btnEditarPersona)
                    .addComponent(btnPracticas))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cargar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPersonaActionPerformed
        crearPersona();
        btnAgregarPersona.setEnabled(false);
        btnEditarPersona.setEnabled(true);
        btnPracticas.setEnabled(true);
    }//GEN-LAST:event_btnAgregarPersonaActionPerformed

    private void btnCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrear1ActionPerformed
        crearArregloPersonas();
        cargarTabla();
        btnCrear1.setEnabled(false);
    }//GEN-LAST:event_btnCrear1ActionPerformed

    private void tblListadoPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListadoPersonasMouseClicked
        if(pc.getPersonas()[tblListadoPersonas.getSelectedRow()].getFechaNacimiento() == null){
            btnAgregarPersona.setEnabled(true);
            btnEditarPersona.setEnabled(false);
            btnPracticas.setEnabled(false);
        }else{
            btnAgregarPersona.setEnabled(false);
            btnEditarPersona.setEnabled(true);
            btnPracticas.setEnabled(true);
            
        }
        
        
    }//GEN-LAST:event_tblListadoPersonasMouseClicked

    private void btnEditarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPersonaActionPerformed
        Integer i = JOptionPane.showConfirmDialog(this, "¿Esta seguro que quiere editar a ");
        if(i == JOptionPane.OK_OPTION){
            crearPersona();
        }else{
            this.dispose();
        }
        
    }//GEN-LAST:event_btnEditarPersonaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (pc.getPersonas() != null){
            if (Utilidades.guardarArchivoJSON(pc.getPersonas())){
                JOptionPane.showMessageDialog(this, "Se ha guardado el archivo","Exito", JOptionPane.INFORMATION_MESSAGE);
            } else JOptionPane.showMessageDialog(this, "No se genero el archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }else JOptionPane.showMessageDialog(this, "Genere un listado de personas", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        pc = new PersonaController(1);
        pc.setPersonas(Utilidades.cargarArchivoJSON());
        
        if (pc.getPersonas()!= null){
            btnCrear1.setEnabled(false);
            cargarTabla();
        } else JOptionPane.showMessageDialog(this, "No pudo cargar el archivo", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tblListadoPersonasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListadoPersonasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblListadoPersonasMousePressed

    private void btnPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPracticasActionPerformed
        diaPractica = new DialogPracticas(this, true);
        diaPractica.setVisible(true);
        Persona p = diaPractica.getPersona();
        if (p != null){
            pc.getPersonas()[tblListadoPersonas.getSelectedRow()].setPracticas(p.getPracticas());
            cargarTabla();
        }
        
        btnPracticas.setEnabled(false);
        
    }//GEN-LAST:event_btnPracticasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    
    public void crearArregloPersonas(){
        pc = new PersonaController(Integer.parseInt(cbxNroPersonas.getSelectedItem().toString()));
        btnAgregarPersona.setEnabled(false);
        pc.imprimirArreglo();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPersona;
    private javax.swing.JButton btnCrear1;
    private javax.swing.JButton btnEditarPersona;
    private javax.swing.JButton btnPracticas;
    private javax.swing.JComboBox<String> cbxNroPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListadoPersonas;
    // End of variables declaration//GEN-END:variables
}
